/**
 * Strict streaming HTTP/1.1 and HTTP/2 requests with bounded transfers,
 * explicit outcomes, and address-pinned network safety.
 *
 * @module
 */

export {
  collectResponseBody,
  disposeResponseBody,
  openResponseBodyFile,
  readResponseBody,
  ResponseBodyCollectionLimitError,
  responseBodyPrefix,
  responseBodySize,
  responseBodyStream,
} from "./body.ts";
export { HttpClientStateError, NodeHttpClient } from "./client.ts";
export {
  HttpClientError,
  HttpConfigurationError,
} from "./errors.ts";
export { HttpFields } from "./fields.ts";
export { defineHttpMethod } from "./method.ts";
export type {
  BufferedHttpRequestOptions,
  BufferedHttpResponse,
  BufferedHttpResult,
  ConnectionFacts,
  ExtensionHttpMethod,
  FileResponseBody,
  HttpAttemptContext,
  HttpAttemptResponseHead,
  HttpAttemptResult,
  HttpAttemptTransfer,
  HttpCancelledAttempt,
  HttpClientConfiguration,
  HttpClientEvent,
  HttpClientObserver,
  HttpCompletedAttempt,
  HttpErrorCode,
  HttpFailedAttempt,
  HttpResponseFailedAttempt,
  HttpFailure,
  HttpField,
  HttpFieldInput,
  HttpFieldsInput,
  HttpMethod,
  HttpRedirect,
  HttpRedirectAttempt,
  HttpRequestBody,
  HttpRequestOptions,
  HttpResponseCompletion,
  HttpSessionAdapter,
  HttpSessionRequestContext,
  HttpSessionResponseContext,
  HttpTimeouts,
  HttpVersion,
  InformationalResponse,
  MemoryResponseBody,
  MixedAddressPolicy,
  MultipartFileContent,
  MultipartPart,
  NetworkAddress,
  NetworkResolver,
  NetworkSafetyOptions,
  PeerCertificateFacts,
  ProtocolPreference,
  ProxyConfiguration,
  RedirectContext,
  RedirectDecision,
  RequestByteStream,
  RequestTimeoutOverrides,
  ResponseBody,
  ResponseBodyCollectionOptions,
  ResponseContentDecoding,
  ResponseHeadTimings,
  ResponseStorageOptions,
  ResponseTransferLimits,
  ResponseTransferTimings,
  StandardHttpMethod,
  StreamingHttpResponse,
  StreamingHttpResult,
  TlsFacts,
  TlsMaterial,
  TlsOptions,
} from "./types.ts";
